### ISSUE TITLE
localconfig-example.txt in 1710

### ISSUE THREAD

**Issue by SvEgiiVEteR** [blay09/DefaultKeyConfig#15]
I have taken you.
# Aroma1997Core

[Aroma1997 / Aroma1997Core.cfg] / sound / muffled Sounds
[Aroma1997 / Aroma1997Core.cfg] / sound / soundsToMuffle
I decided to check
and it so to .minecraft\localconfig.cfg
https://gist.github.com/1fa7ac567b43e36f07317ec9aa5e68df
it is right?
seems to me a mistake.

**Comment by BlayTheNinth** [comment]
I don't really understand what you mean, but the .minecraft\localconfig.cfg is _not_ the one you want to edit.

Instead, edit the one in _.minecraft\config\localconfig.cfg_ and to mark the muffled sounds options as local options, insert

```
[aroma1997/Aroma1997Core.cfg]/sound/muffleSounds
[aroma1997/Aroma1997Core.cfg]/sound/soundsToMuffle
```

Those two options will then no longer get overridden by modpack updates.

**Comment by SvEgiiVEteR** [comment]
@blay09 
Aroma1997Core in the parameter file,
one parameter:
ambient.weather.rain
    # If sounds should get muffled, the sounds to muffle.
    S:soundsToMuffle <
        ambient.weather.rain
     >
}
but your mod wrote 20 pieces probably .
https://gist.github.com/SvEgiiVEteR/1fa7ac567b43e36f07317ec9aa5e68df

**Comment by BlayTheNinth** [comment]
Ah. Yeah, it might be broken. I don't think anyone other than you ever used that particular feature.

**Comment by SvEgiiVEteR** [comment]
I decided to try an additional function in a mod)
and for what I understand, I used your example.
