### ISSUE TITLE
[IDEA] Allow players to save their configs to the cloud

### ISSUE THREAD

**Issue by kreezxil** [blay09/DefaultKeyConfig#20]
For instance, when a pack I'm using has default options, but sometimes they add a new mod that requires them to send that config that overrides all of my changes. If my data was stored in a cloud, I could could load it back with defaultoptions.

I would personally make it compatible with a local directory store, Google drive, Microsoft one drive, and anything that excepts ftp ssh.

**Comment by BlayTheNinth** [comment]
This feature would probably be more suited to a mod like [OptionSync](https://minecraft.curseforge.com/projects/optionsync) which already supports the local directory store.
