### ISSUE TITLE
Saved options/configs dont load

### ISSUE THREAD

**Issue by WorseWaif** [blay09/DefaultKeyConfig#21]
I set up my keybindings, the server, and the options and do /defaultoptions saveall. Then I put the config files I want to be loaded but not overwritten by newer versions. But the configs and the options arent loaded when first loading the modpack. any options or configs I put into the folder, it just recreates those configs and the options file instead as if it doesn't recognize that they are in the defaultoptions folder. I had hoped this would work, as I like having the ability to set it up where any newer versions to fix little things wouldnt completely overwrite the player's setups every time, but with it not working at all, it seems it would be better to just send the files itself...

**Comment by BlayTheNinth** [comment]
What version are you using?

**Comment by WorseWaif** [comment]
I'm so sorry, I've been swamped! I was using the last one released for 1.11.2, DefaultOptions_1.11.2-8.2.2.jar

**Comment by BlayTheNinth** [comment]
The default config files to be copied into the config folder never really worked from what I can tell, and no one ever used it so it just stayed that way. However, Minecraft's settings (options.txt) as well as keybinds are working fine for me.

**Comment by BlayTheNinth** [comment]
For actual mod .cfg files I recommend just shipping them as normal and not relying on Default Options' copy-over feature, as it's broken and unlikely to be fixed for this version. 

If you have issues regarding the default options.txt or default keybindings, please re-open.
