### ISSUE TITLE
[1.12] Can't save any of my settings

### ISSUE THREAD

**Issue by NovaViper** [blay09/DefaultKeyConfig#22]
For some reason, whenever I do try to save all of my settings (or each at a time) or override the default config. the following happens:

- The override-config files is completely blank,  
- All of the entries in the keybinds files all say NONE
- None of my shaders settings are saved

I'm using v9.2.4 that runs on both 1.12 and 1.12.1

**Comment by BlayTheNinth** [comment]
override-config file? Do you mean the overwrite-config file? It shouldn't be there, it's a way of telling the mod to reload all default options and is normally deleted automatically afterwards.

**Comment by NovaViper** [comment]
I made it create the override file, but everything seems to be blank inside it

**Comment by BlayTheNinth** [comment]
It's supposed to be empty.

**Comment by NovaViper** [comment]
Oh, but what about the other settings? Particularly the key bind text, they all say None instead of what the keybind is

_Sent from my Samsung SM-G925P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BlayTheNinth** [comment]
The "NONE" you're seeing is the modifier (SHIFT, CTRL, ALT), the actual key is specified by the number in the file.

What are your "shader" settings? What mod are they from and where are they saved?

**Comment by NovaViper** [comment]
I'm using optifine for the shades, and I I don't see anything else other than NONE with the keybinds

_Sent from my Samsung SM-G925P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BlayTheNinth** [comment]
Optifine probably isn't supported anymore since it loads its options before the game even knows about Default Options' existence. Shouldn't be too big of a deal since Optifine doesn't allow distribution in modpacks most of the time, last I heard.

Pastebin your default options keybinds file then. I've tested it and it works fine here, so I need more information.

**Comment by NovaViper** [comment]
Here's all the files, sorry for not responding sooner
[options.txt](https://github.com/blay09/DefaultOptions/files/1232207/options.txt)
[optionsof.txt](https://github.com/blay09/DefaultOptions/files/1232209/optionsof.txt)
[keybindings.txt](https://github.com/blay09/DefaultOptions/files/1232208/keybindings.txt)

**Comment by BlayTheNinth** [comment]
Those files look fine to me. What, other than OptiFine settings being unsupported, is the problem?

**Comment by NovaViper** [comment]
How would I load the options saved back into the game? Say if I accidentally reset all of my settings in MC to the default

**Comment by BlayTheNinth** [comment]
This mod is for modpack creators to bundle default settings within their modpacks. You're probably looking for something like [OptionSync](https://minecraft.curseforge.com/projects/optionsync).

Default Options loads in the default options once on the first run (or more precisely, when there is no options.txt and no knownkeys.txt files).

**Comment by NovaViper** [comment]
Ah ok. Oh, I think Optifine is still supported, I'm going to test if the shaders work. Also, what does the override config file do and how should I use it?

**Comment by BlayTheNinth** [comment]
It's not supported by this mod is what I meant. The overwrite-config file just tells the mod to copy all .cfg files within the defaultoptions folder to the config folder. You probably shouldn't use it at all.

**Comment by NovaViper** [comment]
Yeah, I just noticed that shaders wasn't. Also, would using the override config file be used to override all the config settings of other mods? Say, I have a certain setting that I want Doggy Talents to have, that override config would do the job to override the default settings of Doggy Talent?

**Comment by BlayTheNinth** [comment]
The overwrite-config stuff is not properly implemented so you should just ignore it. If you want your modpack to come with a defualt Doggy Talent configuration, just put it in the config folder as normal. Default Options only handles options.txt and default keybindings at the moment.
