### ISSUE TITLE
[1.12.2] Default Options and JourneyMap Compat Issue

### ISSUE THREAD

**Issue by SnowShock35** [blay09/DefaultKeyConfig#23]
#### JourneyMap Version:

1.12.2-5.5.2 (Latest at the time)

#### Default Options Version:

1.12.1-9.2.4 (Latest at the time)

#### Forge Version:

1.12.2-14.23.0.2537 (Latest at the time)

#### Describe the problem in repeatable steps:

1. Create a Minecraft Forge instance using the given mods (and their versions) above
2. Load the instance up
3. Go to controls and set all the journey map keybindings to `None` by clicking each one and pressing `Esc`
4. Then save the keybindings and create a new single player world
5. run the command `/defaultoptions saveAll`
6. save and exit the game (close the game down fully)
7. Delete `options.txt` in the instance folder
8. Start Minecraft back up and go to Options > Controls
9. When you scroll down to JoruneyMap you'll see all the key bindings are back to normal again

#### Relevant errors from `.minecraft/journeymap/journeymap.log`:

https://pastebin.com/7Qa7aYsw

***

Disclaimer: Reported the issue both here and https://github.com/TeamJM/journeymap since it only happens w/ JourneyMap and all other mods have no trouble with it.

**Comment by techbrew-mc** [comment]
JM 5.6.0b1 and later will have keybindings registered during init instead of postInit.
