### ISSUE TITLE
FoamFix Anarchy Incompatibility (Solution Inside)

### ISSUE THREAD

**Issue by Noxalas** [blay09/DefaultKeyConfig#25]
Hey there.

I'm currently trying to make my first modpack where I'm also using your mod, but I've stumbled upon a problem. Default Options struggles with replacing my options file, because Minecraft makes one before the mod is able to place it in the folder. The one minecraft makes comes up right after I launch the game and only holds the mipmap level option.

(If I delete the options file that Minecraft creates right as it launches, Default Options works properly and replaces the file as it should.)

Do you maybe have any ideas on what I could do?

**Comment by BlayTheNinth** [comment]
What other mods are installed and what launcher are you using? Sounds like something is trying to set a default on its own.

**Comment by Noxalas** [comment]
I'm running the Twitch Launcher.

Here is the complete mod list:
https://pastebin.com/TY7x7MjV

**Comment by BlayTheNinth** [comment]
It's FoamFix's anarchy version.

https://github.com/asiekierka/FoamFix/blob/3c1d9fbbf8c4018bf8a9dc7981ef2923a4274eda/src/main/java/pl/asie/foamfix/coremod/FoamFixCore.java#L96-L99

It disables mipmapping and enables `B:alwaysSetupTerrainOffThread` on startup before Default Options gets to load. Set `B:initOptions` to `false` in the FoamFix config to prevent it from creating those files, set `B:alwaysSetupTerrainOffThread=true` manually in the forge.cfg, and configure mipmapping as normal in the Default Options way.

**Comment by BlayTheNinth** [comment]
https://github.com/asiekierka/FoamFix/issues/63
