### ISSUE TITLE
[Suggestion] Load a Player's Vanilla Options File

### ISSUE THREAD

**Issue by VT-14** [blay09/DefaultKeyConfig#27]
In lieu of a more comprehensive mod like OptionSync (which doesn't appear to be updated anymore), I would like to be able to transfer at least my vanilla settings to modded instances automatically.

My suggestion would be to load the player's vanilla options, and then apply any modpack overwrites.

In theory, a well configured modpack could distribute only the options they deem important (like setting Mipmap to 0), and then fall back to the player's vanilla preferences for most of the other settings.  It would also give a reason for personal modpack players to download the mod in order to save a few minutes in game.

**Comment by BlayTheNinth** [comment]
I agree something like OptionSync would be useful, but that's not what this mod is. If OptionSync is no longer updating I may consider making a similar solution in the future, but it won't be part of Default Options.

**Comment by BlayTheNinth** [comment]
https://minecraft.curseforge.com/projects/global-settings
