### ISSUE TITLE
Partially not working

### ISSUE THREAD

**Issue by ghost** [blay09/DefaultKeyConfig#29]
The keybindings.txt file copies just fine and my keybindings copy over, but the options.txt file, despite being saved with the correct settings, does not, leaving all GUI settings default.

Forge: 2768
DefaultOptions: 9.2.8

Here's the file it saved in the defaultoptions folder that isn't working: 
[options.txt](https://github.com/blay09/DefaultOptions/files/2671403/options.txt)

**Comment by KaneHart** [comment]
almost 30 days no comment? Anyone else having issues? We tried doing simple stuff by adding them by hand even having like several options. When the game first runs only the mipmapLevels:0 shows up even though that is not there... Like it makes any config invalid unless another mod is forcing to create options file... Hmm I wonder...

**Comment by KaneHart** [comment]
@DemonfangArun I think you can lock this. I scanned the configs for mipmap... Do you have vanillafix installed? That would be it.

**Comment by StoneLegion** [comment]
If you are using FoamFix Anarchy Version, disable B:initOptions in the FoamFix config or else Default Options will not work. See https://github.com/blay09/DefaultOptions/issues/25 for more info.

**Comment by ghost** [comment]
What is going on here? I got 3 emails for this but only one post is showing up.

To answer them:
I do have vanillafix installed, but I don't see how that's related since it's essentially a debug assist tool.
I do have foamfix installed, but not the anarchy version (said version conflicts with other mods in my pack anyway). Reading through that thread, it seems like the issue prevents default options from working at all, what I have is a partial failure (default options can write to options.txt as expected, but only copies over keybindings, and the rest generates as default).

As for the lack of comment, I can only surmise that most people don't use the function to save volume settings and other stuff very much.

**Comment by BlayTheNinth** [comment]
Please post your mod list and a log from Minecraft starting up, some mod is probably generating an options file before Default Options can do anything. The reason keybinds are working fine is that they are handled differently (and stored in a different file).

What kind of options.txt is being generated when Minecraft starts up? That could give hints as to which mod is generating it.

**Comment by ghost** [comment]
Mods list: https://minecraft.curseforge.com/projects/continuity/relations/dependencies + Galcticraft (this is the best way I have to list things, sorry if it's not very great).

Here's a log, startup to main menu then exit: 
[latest.log](https://github.com/blay09/DefaultOptions/files/2752516/latest.log)

And a debug log in case it's useful: 
[debug.log](https://github.com/blay09/DefaultOptions/files/2752521/debug.log)

as for what kind of options file is being generated, I'm not sure what precisely you mean. I'll attach my current one, as it's probably faster:
[options.txt](https://github.com/blay09/DefaultOptions/files/2752512/options.txt)

**Comment by ghost** [comment]
Finally found out what's going on here, after working on squishing ram usage some more. Foamfix anarchy and lawful got merged, and the option mentioned is in the new version simply called foamfix, and is true by default.

Suggested resolution: update the warning on curseforge to reflect this, and make a note of it for future reference.
