### ISSUE TITLE
Integration for Journey Map

### ISSUE THREAD

**Issue by SirAron111** [blay09/DefaultKeyConfig#31]
Is it possible to have the journey map also generate so people will get the minimap settings I made that don’t overlap with anything? Like gui style size, mob heads instead of dots etc.
But without deleting their already generated maps?

**Comment by mysticdrew** [comment]
@blay09 What kind of help do need from my end if you were to implement this?

**Comment by BlayTheNinth** [comment]
JourneyMap support should be possible in the next version using [the new extra default options feature](https://github.com/ModdingForBlockheads/DefaultOptions#extra-default-options).
