### ISSUE TITLE
[1.14.2] Will not launch  with forge .63 - NPE -  Cannot get config value without assigned Config object present

### ISSUE THREAD

**Issue by ProsperCraft** [blay09/DefaultKeyConfig#32]
https://gist.github.com/ProsperCraft/59a473e9ddae346768723c031b6afd3e

1.14.2 modpack - [Skyblock Ocean Islands](https://minecraft.curseforge.com/projects/skyblock-ocean-islands)

**Comment by NielsPilgaard** [comment]
Also happens on 1.14.3 with `Forge-27.0.13` fyi.
