### ISSUE TITLE
[1.14.4] String cannot be cast to net.minecraft.world.Difficulty

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/DefaultKeyConfig#34]
Hello, I've encountered a crash when creating a new world (level-type Biomes O' Plenty, if that makes a difference).

Here's the log: https://gist.github.com/NillerMedDild/95e04ab8c64acc47fc334c5570ecae36

**Comment by BlayTheNinth** [comment]
Wait, I'm dumb and uploaded the exact same broken build again

**Comment by NielsPilgaard** [comment]
Thanks :D
