### ISSUE TITLE
(1.15.2) Unexpected Error occurred trying to excute that command

### ISSUE THREAD

**Issue by BedrockLegends** [blay09/DefaultKeyConfig#37]
anytime I use /defaultoptions saveServers or any other command I get that Unexpected Error occurred trying to excute that command

**Comment by BlayTheNinth** [comment]
Is something being logged on the client/server when you run the commands?

**Comment by BedrockLegends** [comment]
I can look, not sure if its the mod we are using for perms and such causing it

**Comment by BlayTheNinth** [comment]
Closing for now, let me know if this still happens on 1.16+ (and include logs if so)
