### ISSUE TITLE
Crashes upon use.

### ISSUE THREAD

**Issue by MagmaSlime123** [blay09/DefaultKeyConfig#39]
[crash-2020-05-24_22.01.46-server.txt](https://github.com/blay09/DefaultOptions/files/4675279/crash-2020-05-24_22.01.46-server.txt)

[crash-2020-05-24_22.04.43-server.txt](https://github.com/blay09/DefaultOptions/files/4675282/crash-2020-05-24_22.04.43-server.txt)

I'm given these 2 crashes. One when locking the diffaculty, and one when simply logging into a world. Mods and other info listed within the reports.

**Comment by BlayTheNinth** [comment]
This doesn't look like it's related to Default Options. Default Options only does work during loading and when joining a world for the first time, and even then it doesn't do anything that could result in tile entities being changed during loading (which is what this crash seems to be).

**Comment by MagmaSlime123** [comment]
Well, I have no idea, so if you don't mind trying to figure this out then that'd be nice. Besides, crash reports to me are just gabblidoodoo shit that I don't know how to read so... Yeah.

**Comment by BlayTheNinth** [comment]
There's nothing I can do to figure it out, some mod is creating or removing tile entities while the world is being loaded, but from the crashlog it's impossible to tell which one it is. 

If it's happening consistently you could try reproducing it in a test world and removing mods to see when it stops happening. It might also be something in world generation maybe. You'd have to experiment around or see if any of the mods you're using has an open issue report related to this.
