### ISSUE TITLE
[1.12.2] Default keys simply doesn't work whatsoever, even without FoamFix

### ISSUE THREAD

**Issue by aaronhowser1** [blay09/DefaultKeyConfig#40]
On my modpack (which does NOT have FoamFix), I ran `/defaultoptions saveKeys`, which generated 
[keybindings.txt](https://pastebin.com/cqenHi0L) and [options.txt](https://pastebin.com/a8BA49Ek) (pastebin links). Then, I exported the modpack without options.txt, then imported that and ran it.

The music being muted and stuff like that worked, but all keys are set to the normal default rather than what I set them to.

I am using DefaultOptions_1.12.2-9.2.8.

**Comment by Raithion** [comment]
Seconding this, it's like the mod barely works on 1.12.2, and I don't use FoamFix. Keybinds are not saving.

**Comment by BlayTheNinth** [comment]
Works fine for me, make sure to remove both options.txt and knownkeys.txt when shipping the modpack. Could also be that there's a different mod than Foamfix generating an options file now. However, 1.12 is no longer supported.
