### ISSUE TITLE
[1.16.3] defaultoptions/options.txt generates automatically

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/DefaultKeyConfig#46]
The defaultoptions/options.txt is generating on it's own, even though I haven't run the command. Whenever I delete it, it regenerates with my current options as default.

### Versions
- DefaultOptions_1.16.3-12.2.0
- Forge-1.16.3-34.1.25

**Comment by BlayTheNinth** [comment]
I think it's always done that, is there a reason why it shouldn't?

**Comment by NielsPilgaard** [comment]
It used to only generate when the /defaultoptions saveOptions command was used. 
I'd prefer it didn't because I don't want to supply default options, only default keybindings.
