### ISSUE TITLE
[1.16.4] Default Options is not applying resource packs.

### ISSUE THREAD

**Issue by Gliese-832-c** [blay09/DefaultKeyConfig#48]
I want my modpack to come with some resource packs pre-installed, however, it seems to not work.
Here are the files it exported into the defaultoptions config folder after running the command:
[keybindings.txt](https://github.com/blay09/DefaultOptions/files/5851019/keybindings.txt)
[options.txt](https://github.com/blay09/DefaultOptions/files/5851020/options.txt)

Looking into options.txt, you'll find these lines:
```
resourcePacks:["vanilla","quark:emote_resources","file/Unity-1.16.X-Base-2.3.1.zip","file/Unity-1.16.X-Dark-0.6.2.zip","file/Unity-1.16.X-Modded-1.2.0.zip","mod_resources","packmenu"]
incompatibleResourcePacks:["quark:emote_resources","file/Unity-1.16.X-Base-2.3.1.zip","file/Unity-1.16.X-Dark-0.6.2.zip","file/Unity-1.16.X-Modded-1.2.0.zip","packmenu"]
```

You'd think that this would load the resource packs. But for some reason it doesn't.
When I go into [instance]/options.txt, those lines have been replaced with:
```
resourcePacks:["vanilla","mod_resources","packmenu","quark:emote_resources"]
incompatibleResourcePacks:["packmenu","quark:emote_resources"]
```

I hope that it's just user error on my part, but in the worst case, the mod is broken and not loading something. Interestingly, the other options, as well as the keybinds, seem to work.

**Comment by TechnicJelle** [comment]
I seem to be having the same issue, but also with the language setting that doesn't apply.
The strange thing is that, on first launch, if I look in the .minecraft/options.txt file it does say that it's applied correctly, but when I take a look in-game, it isn't.
![image](https://user-images.githubusercontent.com/22576047/105607767-1d711480-5da1-11eb-80fe-d5fbed6bafc6.png)
When I then click the Done button it reloads all the Minecraft resources as usual, but when I then take another look in the options.txt file any mention of the default set resource pack has disappeared.
I also have this problem with the language option that I set to en_gb, but when I load the game for the first time it's set to en_us, but again, in the options.txt it is set to en_gb.
It almost looks like a Minecraft problem instead..

When I set them back manually in-game and look in the options.txt file it's exactly the same as the defaultoptions/options.txt I made, so I'm sure it's not a syntax problem or anything.

Edit after an hour of doing something else:
I just thought of why it would be exactly these two settings and I might know why. I think these two are set even before any mods are loaded in and thus the default options won't have been set yet. I checked my hypothesis and after a clean install, a launch that has the wrong settings I restarted the game and only then did the correct settings apply. So I'm not sure what you could do about this and as such I suppose I'll just tell my players to restart their game once after the first launch just like I did, which is a good enough work-around I guess.

**Comment by dr3ams** [comment]
If anyone still having this issue:
Check if any of your enabled resourcepacks has the **'** symbol
Looked like this in options.txt: `"file/Botany\u0027s+Lush+Leaves.zip"` and like this `Botany's+Lush+Leaves.zip` in resourcepacks folder. 
Wasn't working until I disabled the RP.
