### ISSUE TITLE
Fabric port?

### ISSUE THREAD

**Issue by NebelNidas** [blay09/DefaultKeyConfig#51]
I'm currently putting together a modpack and am quite unhappy about the many unnecessary and conflicting keybinds. I use MCUpdater, but I fear it will override the user's own options.txt every time I update the pack, which lead me to your mod. Unfortunately it's Forge-only, so I wanted to ask if you would consider a Fabric port?

**Comment by BlayTheNinth** [comment]
no

**Comment by NebelNidas** [comment]
Well, that's what I call a comprehensive answer! I guess I'll port it myself then. 🤷‍♂️

**Comment by BlayTheNinth** [comment]
I'm not gonna record an apology video every time someone asks me to port to Fabric. Regardless, issue trackers are not the right place for questions like these.
