### ISSUE TITLE
[Request] Generalised API for Mods to Distrubute Custom Option Files

### ISSUE THREAD

**Issue by starmun-0010** [blay09/DefaultKeyConfig#54]
Instead of working on compatibility for individual mods, it would be really nice to have an API. An API which would enable developers of any mod with custom option files to distribute their files via the Default Options.

This request is in self-interest too, my mod [Just Enough Keys](https://www.curseforge.com/minecraft/mc-mods/just-enough-keys-fabric) depends on its own custom keybinding file and It would be lovely if I could distribute the file via **Default Options**.

**Comment by BlayTheNinth** [comment]
Refactored the mod and added a simple API, not sure if it can do what you need yet but let me know if you have any ideas for improvement
