### ISSUE TITLE
Keybinds are not applied

### ISSUE THREAD

**Issue by MelanX** [blay09/DefaultKeyConfig#55]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.9

### Mod Version

1.18-14.0.0

### Describe the Issue

Keybinds are not applied.

## Reproduce
1. Setup the `options/defaultoptions/keybindings.txt`
2. Start MC
3. Look at controls or `options.txt`
4. No keybinds :(

## Problem
I'd say that you forgot to apply the `keybinds.txt`.
Look here: https://github.com/ModdingForBlockheads/DefaultOptions/blob/1.18.x/shared/src/main/java/net/blay09/mods/defaultoptions/DefaultOptionsInitializer.java#L55-L73
You create the `options.txt` but don't read the `keybinds.txt`. Maybe it's the wrong position and I'm wrong.

### Logs

https://gist.github.com/MelanX/b2c435ea0bf82cba313f78405dae7f93

### Do you use any performance-enhancing mods (e.g. OptiFine)?

no

**Comment by Gbergz** [comment]
Can confirm.

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm & Default Options
