### ISSUE TITLE
[1.18.1] JourneyMap Compatibility- default keybindings for Journey Map not working. 

### ISSUE THREAD

**Issue by Gbergz** [blay09/DefaultKeyConfig#56]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.10

### Mod Version

1.18-14.0.0

### Describe the Issue

Journey Map keybinds set in the Default Options .txt file always get reset to stock default controls when installing a new instance.
Example: Changed new waypoint from B to P. When installing modpack it's still on B even though P is set in default options.

Only mod that I've encountered that does this.

Thanks,
**-** Gbergz

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Nope.

**Comment by CthonicSyzygies** [comment]
I was encountering this bug too. It looks like an issue with JourneyMap that they've got set to correct. https://github.com/TeamJM/journeymap/issues/375#issuecomment-1013502686

**Comment by Gbergz** [comment]
@CthonicSyzygies Not sure that's the exact issue I have.. but maybe it'll be fixed automatically with beta9 then.

**Comment by Gbergz** [comment]
Nope, not fixed by using Beta9. :s

**Comment by mysticdrew** [comment]
> I was encountering this bug too. It looks like an issue with JourneyMap that they've got set to correct. [TeamJM/journeymap#375 (comment)](https://github.com/TeamJM/journeymap/issues/375#issuecomment-1013502686)

completely different issue.

**Comment by mysticdrew** [comment]
I cannot get this to work correctly, at the time this issue was created we were registering our keybindings during the `FMLLoadCompleteEvent`. I have since switched it to register them during the `FMLClientSetupEvent`. It still does not work. 
maybe @blay09 will have some insight into this.

**Comment by mysticdrew** [comment]
> I cannot get this to work correctly, at the time this issue was created we were registering our keybindings during the `FMLLoadCompleteEvent`. I have since switched it to register them during the `FMLClientSetupEvent`. It still does not work. maybe @blay09 will have some insight into this.

My inability to get it to work could be related to #55

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm & Default Options
