### ISSUE TITLE
[1.18.2] Default options crashes the pack now that I have configured it.

### ISSUE THREAD

**Issue by ProsperCraft** [blay09/DefaultKeyConfig#62]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.48

### Mod Version

defaultoptions-forge-1.18.1-14.1.0.jar

### Describe the Issue

I had launched the modpack many times with no crashing, then when I had /defaultoptions saveall in single player then launched again, it crashes now.

### Logs

https://gist.github.com/ProsperCraft/e2abb893195246d83a03633420d3d308   https://gist.github.com/ProsperCraft/993b6d09926c7aeeea0bd8d404f6543d

**Comment by BlayTheNinth** [comment]
Should be fixed by Balm 3.1+
