### ISSUE TITLE
Crash on selecting singleplayer

### ISSUE THREAD

**Issue by Enterprise12nx01** [blay09/DefaultKeyConfig#63]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.35

### Mod Version

DefaultOptions_1.16.5-12.2.1.jar

### Describe the Issue

Before even saving default options, when you select singleplayer it crashes the client.
Reported on another thread with more details here:
https://github.com/Shadows-of-Fire/PackMenu/issues/41

### Logs

Debug.log provided in above post

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Rubidium, Oculus, Rubidium/Magnesium extras, Roadrunner

**Comment by BlayTheNinth** [comment]
1.16 is no longer supported and the logs paste has expired. Most likely this was a conflict with another mod in the pack as this does not seem to be a widespread issue.
