### ISSUE TITLE
Support for Amecs

### ISSUE THREAD

**Issue by Dekamir** [blay09/DefaultKeyConfig#66]
Amecs is a mod that allows having modifier keys on keybinds.
The modifier config is kept in a different file called **options.amecsapi.txt**.
It would be nice if DefaultOptions also supported this file.

**Comment by raws** [comment]
You can do this today using Default Options' ["extra default options" feature](https://github.com/TwelveIterationMods/DefaultOptions/tree/3ad8544934723d398f9d9007bd345227a134d6b1#extra-default-options)! Create `config/defaultoptions/extra/options.amecsapi.txt`, and it'll be copied to `.minecraft/options.amecsapi.txt` if it doesn't already exist.

It doesn't get the fancy known key handling as with `options.txt` and `knownkeys.txt`, but it works well enough for me.

edit: though worth mentioning, Default Options 15.0.0 seems to be affected by #65, which causes files in `config/defaultoptions/extra` to always overwrite existing files in the Minecraft game directory, regardless of whether they already exist.

**Comment by WimpieRatte** [comment]
Just encountered this now as well and glad I see there's already a request for this :D.

**Comment by Dekamir** [comment]
I would love to see this backported to 1.19.2, but even if it doesn't get it, thanks for the work.
