### ISSUE TITLE
DefaultConfig extra not working....

### ISSUE THREAD

**Issue by IPECTER** [blay09/DefaultKeyConfig#76]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Mod Loader Version

Fabric 0.15.7

### Mod Version

20.0.1

### Balm Version

9.0.6

### Describe the Issue

continued from https://discord.com/channels/1065604459104829480/1211173789044318218

No extra config.....
https://youtu.be/v7KvlGLJN7o

### Logs

https://pastebin.com/WdzZhLtS

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Check video!

**Comment by IPECTER** [comment]
I can wait all day..

**Comment by BlayTheNinth** [comment]
It looks like this is an issue specifically with Sodium/Iris configs. It could be that they are loading their options very early, before Default Options has a chance to provide its defaults.

I've released a new version of Default Options that tries to apply the defaults a little earlier, but I'm not sure if it will fix this particular issue. If it doesn't there's not really anything I can do without adding explicit support for those mods, which is not something I plan to do at the moment.

**Comment by IPECTER** [comment]
2 weeks ago, I edited mixin inject point before iris/sodium init config mixin, It works.
Anyway, Thx for fix!

have a nice day!
