### ISSUE TITLE
Game difficulty will be changed unexpectly

### ISSUE THREAD

**Issue by GoldenTotem** [blay09/DefaultKeyConfig#77]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

Forge 36.2.35

### Mod Version

1.16.5 - 12.2.1

### Balm Version

none

### Describe the Issue

Steps to Reproduce:
1. Click SinglePlayer
2. Click Create New World
3. Change the difficulty to hard or easy or peaceful
4. Click Game Rules or Data Packs or More world option to go to another page
5. Go back to the create new world page, you will find the game difficulty was changed to normal
6. It seems the mod will always change the difficulty to the difficulty specified in the config when the create new world page opened

What I expected to happen was...:
Changing the difficulty to which specified in the config only when clicking Create New World at Select World page, just like vanilla. If I change difficulty firstly and then come back from gamerule page, I will not notice difficulty and it will be changed unexpectly.

**Comment by BlayTheNinth** [comment]
Fixed in 1.20.4, but 1.16.5 is no longer supported.
