### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by bruglet** [blay09/DefaultKeyConfig#78]
Hi, will you consider uploading your mod to Modrinth as well, in order for Modrinth modpacks to use your mod (without asking you explicit permission)?

Modrinth supports creator payouts if that is a concern.

**Comment by brug-dev** [comment]
Wait I didn't realize that Modrinth was already supported but that is not indicated in the README.md.

https://modrinth.com/mod/default-options

Sorry 😅

**Comment by bruglet** [comment]
Wait I didn't realize that Modrinth was already supported but that is not indicated in the README.md.

https://modrinth.com/mod/default-options

Sorry 😅
