### ISSUE TITLE
keybinding.txt is not applying to files on first launch

### ISSUE THREAD

**Issue by xCykrix** [blay09/DefaultKeyConfig#81]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

Fabric 1.21 - Loader 0.51.11

### Mod Version

21.0.4+fabric-1.21

### Balm Version

21.0.9+fabric-1.21

### Describe the Issue

When providing keybinds.txt, changes are not being applied to the default control layout on first boot.

Attached simplified Modrinth mrpack file to replicate. I have many performance mods, but all are disabled besides Balm, Default Options, and Fabric API.

This may just be user error, but I am unable to identify why the default keybinds are not being loaded.

### Logs

https://mclo.gs/s9tLH9T

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

See Description of Issue

**Comment by xCykrix** [comment]
[1.21 - Replicate 1.0.0.zip](https://github.com/user-attachments/files/16007676/1.21.-.Replicate.1.0.0.zip)

You can change this to .mrpack or just load the zip file into Modrinth. options.txt is working as expected, so I know the mod is doing something... I just don't know what is happening here.

**Comment by FaultyFunctions** [comment]
I am also running into this issue.
